content: |-
  {{ .Header }}

  ## Usage

  The `map_roles`, `map_users`, and `map_accounts` will be merged with the managed node group and fargate profile roles and added to the `aws-auth` configmap.

  ```hcl
  {{ include "examples/complete/complete.tf.docs" }}
  ```

  Please see the [complete example](examples/complete) for more information.

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Modules }}

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}
