content: |-
  {{ .Header }}

  # Usage

  The `aws-auth` configmap will be replaced with a new configmap merged with the additional roles, users, and accounts.

  ```hcl
  module "eks" {
    source  = "terraform-aws-modules/eks/aws"
    ...
  }

  module "eks_auth" {
    source = "aidanmelen/eks-auth/aws"
    eks    = module.eks

    map_roles = [
      {
        rolearn  = "arn:aws:iam::66666666666:role/role1"
        username = "role1"
        groups   = ["system:masters"]
      },
    ]

    map_users = [
      {
        userarn  = "arn:aws:iam::66666666666:user/user1"
        username = "user1"
        groups   = ["system:masters"]
      },
      {
        userarn  = "arn:aws:iam::66666666666:user/user2"
        username = "user2"
        groups   = ["system:masters"]
      },
    ]

    map_accounts = [
      "777777777777",
      "888888888888",
    ]
  }
  ```

  Please see [examples/complete](examples/complete) for more information.

  ## Patch ConfigMap

  The aws-auth configmap will be patched in-place with additional roles, users, and accounts.

  ```hcl
  module "eks" {
  source  = "terraform-aws-modules/eks/aws"
    ...
  }

  module "eks_auth" {
    source = "aidanmelen/eks-auth/aws"
    eks    = module.eks
    patch  = true
  }
  ```

  Please see [examples/patch](examples/patch) for more information.

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Modules }}

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}
