content: |-
  {{ .Header }}

  # Usage

  The `aws-auth` configmap will be replaced with a new configmap merged with the additional roles, users, and accounts.

  ```hcl
  {{ include "docs/snippets/complete.tf" }}
  ```

  Please see [examples/complete](examples/complete) for more information.

  ## Patch ConfigMap

  The aws-auth configmap will be patched in-place and will not be managed with Terraform state.

  ```hcl
  {{ include "docs/snippets/patch.tf" }}
  ```

  Please see [examples/patch](examples/patch) for more information.

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Modules }}

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}
