content: |-
  {{ .Header }}

  ## Usage

  The roles, users, and accounts will be merged with the cluster roles and added to a new `aws-auth` configmap managed with Terraform state.

  ```hcl
  {{ include "examples/complete/complete.tf.docs" }}
  ```

  Please see the [complete example](examples/complete) for more information.

  Please see the [patch example](examples/patch) for more information.

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Modules }}

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}
